### ISSUE TITLE
No weather data due API change

### ISSUE THREAD

**Issue by twSimulations** [aloys-c/wx2pfpx#6]
wx2pfpx does not download any data. I guess this has to do with the API change lately?!

**Comment by aloys-c** [comment]
Hi,

The problem is not due to the NOAA api change, the wind dataset is still downlading well. The issue is on the metar and taf data source api...

I don't have much time at the moment to take care of the issue, If you're motivated I would suggest finding someone that can fork the repo and continue maintaining it.

**Comment by PinkPony89** [comment]
> wx2pfpx does not download any data. I guess this has to do with the API change lately?!

I implemented the new NOAA API. 

Use this version:

[wx2pfpx2.6.zip](https://github.com/aloys-c/wx2pfpx/files/13064109/wx2pfpx2.6.zip)


As Aloys suggested, I am going to fork the repo.
